//go:build ignore

package main

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
)

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: go run ./minilm/generate_vocab.go vocab.txt minilm/vocab_gen.go")
		os.Exit(2)
	}
	in, err := os.Open(os.Args[1])
	if err != nil {
		panic(err)
	}
	defer in.Close()

	out, err := os.Create(os.Args[2])
	if err != nil {
		panic(err)
	}
	defer out.Close()

	fmt.Fprintln(out, "package minilm")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "// Code generated by minilm/generate_vocab.go; DO NOT EDIT.")
	fmt.Fprintln(out, "var rawVocab = []vocabEntry{")
	scanner := bufio.NewScanner(in)
	id := 0
	for scanner.Scan() {
		token := strings.TrimSpace(scanner.Text())
		if token == "" {
			continue
		}
		fmt.Fprintf(out, "\t{Token: %s, ID: %d},\n", strconv.Quote(token), id)
		id++
	}
	if err := scanner.Err(); err != nil {
		panic(err)
	}
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "func Vocab() map[string]int {")
	fmt.Fprintln(out, "\tvocab := make(map[string]int, len(rawVocab))")
	fmt.Fprintln(out, "\tfor _, entry := range rawVocab {")
	fmt.Fprintln(out, "\t\tvocab[entry.Token] = entry.ID")
	fmt.Fprintln(out, "\t}")
	fmt.Fprintln(out, "\treturn vocab")
	fmt.Fprintln(out, "}")
}
